name: Reusable test workflow

on: [workflow_call]

jobs:
  codeInspection:
    name: Code Inspection
    runs-on: ubuntu-latest
    steps:

      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Qodana - Code Inspection
        uses: JetBrains/qodana-action@v2022.3.0
