name: Reusable Code Inspection

on: [ workflow_call ]

env:
  XDG_CACHE_HOME: "~/.config/"

jobs:
  codeInspection:
    name: Code Inspection
    runs-on: ubuntu-latest
    steps:

      - name: Fetch Sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # only report issues that appeared in a PR

      - name: Qodana - Code Inspection
        uses: JetBrains/qodana-action@v2022.3.2
        if: ${{ false }}  # disable for now
